### PR TITLE
Boilerplate for `EventList` / `EventListWeb`

### PR DESCRIPTION
**Pull request by russellmatbouli**
This is the boilerplate code generated while pairing with @holsee at the November BelfastElixir meetup. 🌃

### CODE REVIEW

**Comment by pablobm** [comment]
Is this just the result of running a generator, or are there more changes?

**Comment by russellmatbouli** [comment]
Sorry @pablobm , only noticed this when I logged in for Hacktoberfest :/

This was created with a generator, I don't think we added any other changes, right @holsee?

Would be good to pick this up again, admittedly meetups haven't been a priority recently...

**Review by holsee — COMMENTED** [review]
This was just boilerplate, if we pick this up in future we will likely run the init generator again with the latest versions of elixir, phoenix etc.

I recommend closing this PR without a merge.

**Comment by holsee** [comment]
Yup, just boilerplate.

I will close this issue simply because it has been open for so long :)

**Pull request closed without merging**
